services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - appnet

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - appnet

  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: myuser
      RABBITMQ_DEFAULT_PASS: secret
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - appnet

  api-blue:
    image: hashicorp/http-echo:1.0.0
    command: ["-listen=:8080", "-text=BLUE"]
    networks:
      - appnet

  api-green:
    image: hashicorp/http-echo:1.0.0
    command: ["-listen=:8080", "-text=GREEN"]
    networks:
      - appnet

  nginx:
    image: nginx:1.27-alpine
    depends_on:
      - api-blue
      - api-green
    ports:
      - "80:80"
    volumes:
      - ./Infra/infra/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./Infra/infra/nginx/upstreams:/etc/nginx/upstreams:ro
    networks:
      - appnet

  prometheus:
    image: prom/prometheus:v3.5.0
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    ports:
      - "9090:9090"
    volumes:
      - ./Infra/infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    networks:
      - appnet

  grafana:
    image: grafana/grafana:12.1.1
    depends_on:
      - prometheus
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - appnet

networks:
  appnet:
    driver: bridge

volumes:
  pg_data:
  redis_data:
  rabbitmq_data:
  prometheus_data:
  grafana_data:
