services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.1
    container_name: stg-keycloak
    restart: unless-stopped
    command:
      - start
      - --import-realm
      - --http-enabled=true
      - --hostname=auth.ssafymaker.cloud
      - --hostname-strict=false
      - --proxy-headers=xforwarded
    environment:
      KC_DB: postgres
      KC_DB_URL: ${KEYCLOAK_DB_URL}
      KC_DB_USERNAME: ${KEYCLOAK_DB_USER}
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    volumes:
      - ./keycloak/realm:/opt/keycloak/data/import:ro
    networks:
      - core-net

networks:
  core-net:
    external: true
    name: s14p21e206_core_net
