services:
  postgres:
    image: ${POSTGRES_IMAGE}
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - core-net
    ports:
      - "127.0.0.1:5432:5432"

  redis:
    image: ${REDIS_IMAGE}
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - core-net
    ports:
      - "127.0.0.1:6379:6379"

  rabbitmq:
    image: ${RABBITMQ_IMAGE}
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - core-net
    ports:
      - "127.0.0.1:5672:5672"
      - "127.0.0.1:15672:15672"

networks:
  core-net:
    name: s14p21e206_core_net


volumes:
  pg_data:
    name: s14p21e206_pg_data
  redis_data:
    name: s14p21e206_redis_data
  rabbitmq_data:
    name: s14p21e206_rabbitmq_data