spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/mydatabase}
    username: ${DB_USER:myuser}
    password: ${DB_PASSWORD:secret}
  jpa:
    hibernate:
      ddl-auto: validate
  docker:
    compose:
      enabled: false

app:
  security:
    jwt:
      enabled: ${JWT_ENABLED:false}
